import { Request, Response } from 'express';
import { z } from 'zod';
import { assignmentService } from './assignment.service';
import { classroomService } from '../classroom/classroom.service';

const createSchema = z.object({
  title: z.string().min(1, 'Title is required'),
  description: z.string().optional(),
  language: z.string().min(1, 'Language is required'),
  difficulty: z.string(),
  marks: z.number().min(1),
  timeLimitMinutes: z.number().optional(),
  dueDate: z.string().optional(),
  conceptsCovered: z.array(z.string()).optional(),
  visibleTestCases: z.array(z.object({
    input: z.string(),
    expectedOutput: z.string()
  })).optional(),
  hiddenTestCases: z.array(z.object({
    input: z.string(),
    expectedOutput: z.string()
  })).optional(),
  hints: z.array(z.object({
    level: z.number(),
    text: z.string()
  })).optional()
});

export const assignmentController = {
  async create(req: Request, res: Response) {
    try {
      const user = (req as any).user;
      const { classroomId } = req.params;
      
      const classroom = await classroomService.getClassroomById(classroomId);
      if (!classroom || classroom.teacher_id !== user.userId) {
        res.status(403).json({ message: 'Forbidden' });
        return;
      }

      let validated = createSchema.parse(req.body);

      // Auto-generate test cases and hints if they are missing
      if ((!validated.visibleTestCases || validated.visibleTestCases.length === 0) &&
          (!validated.hints || validated.hints.length === 0)) {
        const aiService = require('../ai/ai.service');
        const autoGenerated = await aiService.generateTestCasesFromDescription(
          validated.title, 
          validated.description || '', 
          validated.language
        );
        
        validated.visibleTestCases = autoGenerated.visibleTestCases;
        validated.hiddenTestCases = autoGenerated.hiddenTestCases;
        validated.hints = autoGenerated.hints;
      }

      const assignment = await assignmentService.createAssignment(classroomId, validated);
      
      res.status(201).json(assignment);
    } catch (error: any) {
      if (error instanceof z.ZodError) {
        res.status(400).json({ errors: error.errors });
      } else {
        console.error(error);
        res.status(500).json({ message: 'Internal server error' });
      }
    }
  },

  async publish(req: Request, res: Response) {
    try {
      const user = (req as any).user;
      const { id } = req.params;

      const assignment = await assignmentService.getAssignmentById(id);
      if (!assignment) {
        res.status(404).json({ message: 'Not found' });
        return;
      }

      // Check ownership
      const classroom = await classroomService.getClassroomById(assignment.classroom_id);
      if (!classroom || classroom.teacher_id !== user.userId) {
        res.status(403).json({ message: 'Forbidden' });
        return;
      }

      await assignmentService.publishAssignment(id);
      res.status(200).json({ success: true });
    } catch (error) {
      res.status(500).json({ message: 'Internal server error' });
    }
  },

  async getByClassroom(req: Request, res: Response) {
    try {
      const { classroomId } = req.params;
      const assignments = await assignmentService.getAssignmentsByClassroom(classroomId);
      res.status(200).json(assignments);
    } catch (error) {
      res.status(500).json({ message: 'Internal server error' });
    }
  },

  async getById(req: Request, res: Response) {
    try {
      const { id } = req.params;
      const assignment = await assignmentService.getAssignmentById(id);
      if (!assignment) {
        res.status(404).json({ message: 'Not found' });
        return;
      }
      res.status(200).json(assignment);
    } catch (error) {
      res.status(500).json({ message: 'Internal server error' });
    }
  },

  async deleteAssignment(req: Request, res: Response) {
    try {
      const { id } = req.params;
      await assignmentService.deleteAssignment(id);
      res.status(200).json({ success: true, message: 'Assignment deleted successfully' });
    } catch (error) {
      console.error(error);
      res.status(500).json({ message: 'Internal server error' });
    }
  },

  async getAnalytics(req: Request, res: Response) {
    try {
      const { id } = req.params;
      const analytics = await assignmentService.getAnalytics(id);
      res.status(200).json(analytics);
    } catch (error) {
      res.status(500).json({ message: 'Internal server error' });
    }
  },

  async generate(req: Request, res: Response) {
    try {
      const { topic, marks, difficulty, language } = req.body;
      const aiService = require('../ai/ai.service');
      const generated = await aiService.generateAssignment(topic, marks, difficulty, language);
      res.status(200).json(generated);
    } catch (error) {
      res.status(500).json({ message: 'Internal server error' });
    }
  },

  async run(req: Request, res: Response) {
    try {
      const { id } = req.params;
      const { sourceCode, language } = req.body;
      
      const assignment = await assignmentService.getAssignmentById(id);
      if (!assignment) return res.status(404).json({ message: 'Assignment not found' });
      
      const visibleTestCases = assignment.testCases.filter((tc: any) => !tc.is_hidden);
      
      const { codeExecutionService } = require('./codeExecutionService');
      const results = [];
      
      for (let i = 0; i < visibleTestCases.length; i++) {
        const tc = visibleTestCases[i];
        const execResult = await codeExecutionService.executeCode(sourceCode, assignment.language, tc.input);
        
        const actualOutput = execResult.stdout.trim();
        const expectedOutput = tc.expected_output.trim();
        const passed = actualOutput === expectedOutput && !execResult.error;
        
        results.push({
          id: tc.id,
          testCaseNumber: i + 1,
          input: tc.input,
          expectedOutput: tc.expected_output,
          actualOutput: execResult.error ? `Error: ${execResult.error}\n${execResult.stderr}` : actualOutput,
          passed
        });
      }
      
      res.status(200).json({ results });
    } catch (error) {
      console.error(error);
      res.status(500).json({ message: 'Internal server error' });
    }
  },

  async hint(req: Request, res: Response) {
    try {
      const { id } = req.params;
      const { level } = req.body;
      const assignment = await assignmentService.getAssignmentById(id);
      if (!assignment) return res.status(404).json({message: 'Not found'});
      
      const hint = assignment.hints.find((h: any) => h.level === level);
      if (!hint) return res.status(404).json({message: 'Hint not found'});
      
      res.status(200).json({ hint: hint.hint_text });
    } catch (error) {
      res.status(500).json({ message: 'Internal server error' });
    }
  },

  async submit(req: Request, res: Response) {
    try {
      const user = (req as any).user;
      const { id } = req.params;
      const { sourceCode, language } = req.body;

      // 1. Create submission
      const submission = await assignmentService.createSubmission(id, user.userId, language, sourceCode);

      // 2. Execute Code
      const assignment = await assignmentService.getAssignmentById(id);
      let passedCount = 0;
      const totalTests = assignment.testCases.length;
      let executionResults = [];
      
      const { codeExecutionService } = require('./codeExecutionService');

      for (let i = 0; i < assignment.testCases.length; i++) {
        const tc = assignment.testCases[i];
        const execResult = await codeExecutionService.executeCode(sourceCode, assignment.language, tc.input);
        
        const actualOutput = execResult.stdout.trim();
        const expectedOutput = tc.expected_output.trim();
        const passed = actualOutput === expectedOutput && !execResult.error;
        
        const finalActualOutput = execResult.error ? `Error: ${execResult.error}\n${execResult.stderr}` : actualOutput;
        
        await assignmentService.saveSubmissionResult(submission.id, tc.id, passed, finalActualOutput);
        
        executionResults.push({
          id: tc.id,
          testCaseNumber: i + 1,
          input: tc.input,
          expectedOutput: tc.expected_output,
          actualOutput: finalActualOutput,
          passed,
          isHidden: tc.is_hidden
        });
        
        if (passed) passedCount++;
      }

      const score = totalTests > 0 ? Math.round((passedCount / totalTests) * assignment.marks) : 0;
      let status = 'Failed';
      if (totalTests === 0) {
        status = 'Needs Review';
      } else if (passedCount === totalTests) {
        status = 'Passed';
      }
      await assignmentService.updateSubmissionStatus(submission.id, status, score, 50, 1024);

      // 3. AI Analysis
      const aiService = require('../ai/ai.service');
      const analysis = await aiService.analyzeSubmission(sourceCode, language, executionResults);
      await assignmentService.saveAIRecommendation(id, user.userId, analysis.recommendationText, analysis.conceptGap);

      // 4. Broadcast live update to classroom
      const { io } = require('../../server');
      if (io) {
        io.to(`classroom:${assignment.classroom_id}`).emit('classroom:activity-update', {
          student_id: user.userId,
          status: 'submitted',
          score,
          marks: assignment.marks
        });
      }

      res.status(200).json({ 
        submissionId: submission.id,
        status,
        score,
        results: executionResults 
      });
    } catch (error) {
      console.error(error);
      res.status(500).json({ message: 'Internal server error' });
    }
  }
};
